id: mv
title: mv - move / rename files and folders

type: command
command: mv

aliases:
  - mv
  - move a file
  - move a directory

keywords:
  - mv
  - move
  - rename
  - destination

related:
  - rename-folder

intent:
  - explain
  - command

difficulty: beginner
platforms:
  - linux
tags:
  - filesystem
examples:
  - mv -i -- SOURCE DESTINATION
